# Generated by Django 4.1.13 on 2024-03-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipeImage',
            field=models.ImageField(default='default_image.jpg', upload_to='recipe_images/'),
        ),
    ]
